added a feature up update a node and updated the help / readme

diff --git a/files/clim b/files/clim
--- a/files/clim
+++ b/files/clim
@@ -20,22 +20,36 @@ while getopts "ch?no:l:" opt; do
    case "$opt" in
    h|\?)
      cat <<EOF
+clim is a wrapper for the asible based cloud lifecycle manager used in SUSE OpenStack Cloud 8. It will call the ansible playbooks in the correct directory and combines some steps to simplify the installation. It starts long running tasks inside of a screen session - which will not break a job due to a session disconnect. There is also an option to sent a pushover notification to a mobile, after the taks is done (www.pushover.net).
 HELP:
   -c                                   :run config-processor with option "-e remove_deleted_servers=True -e free_unused_addresses=True"
-  -o "<OPTIONS>"                       :add <OPTIONS> to the end of the ansoble-playbook call
-  -l "<RESOURCE>"                      :if the service command is used, limit the execution to the resource <RESOURCE>
+  -o "<OPTIONS>"                       :add <OPTIONS> to the end of the ansible-playbook call
+  -l "<RESOURCE>"                      :if the service command is used, limit the execution to the resource <RESOURCE> (= --limit <RESOURCE>
   -n notify via pushover	       : Pushover is a service to push notifications to a mobile (other clients are possible). The credentials for the service
                                          have to be configured in ~/.clim  
 
 COMMANDS
   prepare "MESSAGE"                    : commits the config changes, run the config-processor and run the ready-deployment if the config is valid
-  site                                 : deploys the config to the nodes via the site.yml playbook
-  status	                       : checks the status of the services
-  stop		                       : shutdown the openstack services
-  start		                       : start the openstack services
+  site                                 : deploys the config to the nodes via the site.yml playbook. It will stop if there are uncommited changes in the input model
+  status	                       : checks the status of the services. Use "-l <RESOURCE>" to get the status only for <RESOURCE>
+  stop		                       : shutdown the openstack services. Use "-l <RESOURCE>" to stop the service only for <RESOURCE>
+  start		                       : start the openstack services. Use "-l <RESOURCE>" to start the services only for <RESOURCE>
+  reboot <RESOURCE>		       : reboot the node <RESOURCE> gracefully (stop the services, reboot the node and start the services again)
+
   service <OPENSTACK-SERVICE> <ACTION> : runs the ansible playbook to execute <ACTION> on the service <OPENSTACK>
-                                         e.x.: "clim service neutron restart"
+                                         e.x.: "clim service neutron restart". Use "-l <RESOURCE>" to start the acttion only on <RESOURCE>
   service list                         : list all services
+  cobbler-deploy		       : executes the cobbler-deploy playbook
+  prepare-sles-grub2i <NODES>          : prepare the pxe install environemnet for <NODE> - executes the prepare-sles-grub2 runbook for <RESOURCE>
+  bm-reimage <NODES>                   : reinstall the node <NODE> (or <NODE1,NODE2,NODE3) via cobbler
+  bm-power-status <NODES>	       : show the power status of <NODE>
+  wipe-disks <NODES>                   : Wipe the disks of <NODES>
+  
+  update-node <RECOURCE>	       : updates a node: apply all patches, update ardana and show the update-status of the node. 
+                                         Patches which need a reboot are included, but the node will not rebooted automatically.
+
+  show_nic_mapping <IP>		       : displays the NIC mappings of the server in a template format, which can be used to add a new mappings to  nic_mappings.yml
+  
   setup_bashrc	                       : crates a .bashrc file and setup variables which can be used as a shortcut for jumping in the correct directory:
                                           - \$def=~/openstack/my_cloud/definition
                                           - \$data=~/openstack/my_cloud/definition/data
@@ -127,7 +141,15 @@ case "$1" in
 
         reboot)
           cd ~/scratch/ansible/next/ardana/ansible || exit
-          ansible-playbook -i hosts/verb_hosts ardana-reboot.yml $options
+          nodes=""
+          if [ ! -z $2 ]
+              then
+                 nodes="--limit $2"
+	      else
+                echo "ERROR: node name is missing: clim reboot <RESOURCE>"
+                exit 1
+          fi
+          ansible-playbook -i hosts/verb_hosts ardana-reboot.yml $nodes
           ;;
 
         service)
@@ -173,6 +195,9 @@ case "$1" in
               if [ ! -z $2 ]
                   then
                    nodes="-e nodelist=$2"
+                  else
+                   echo "<RESOURCE> is missing !"
+                   exit 1
 	      fi
               ansible-playbook -i hosts/localhost bm-reimage.yml $nodes
 	 ;;
@@ -191,13 +216,16 @@ case "$1" in
               if [ ! -z $2 ]
                   then
                    nodes="--limit $2"
+                  else
+                   echo "<NODES> missing: run clim wipe-disks <NODES>"
+                   exit 1
               fi
               ansible-playbook -i hosts/localhost wipe_disks.yml $nodes
          ;;
-        nic_mapping)
+        show_nic_mapping)
               if [ -z $2 ]
                  then
-                   echo "clim nic_mapping <SERVERNAME>"
+                   echo "clim show_nic_mapping <SERVERNAME>"
                    exit 1
               fi
               ping -c 1 $2 >>/dev/null
@@ -221,6 +249,27 @@ EOF
               done
           ;;
 
+       update-node)
+              if [ -z $2 ]
+                 then
+                   echo "SERVER Name missing"
+                   exit 1
+              fi
+          cd ~/scratch/ansible/next/ardana/ansible
+          ansible-playbook -i hosts/verb_hosts ardana-update-pkgs.yml -e zypper_update_include_reboot_patches=true --limit $2
+          if [ $? -ne 0 ]
+                then
+                  echo "ERROR"
+                  exit 2
+          fi
+          ansible-playbook -i hosts/verb_hosts ardana-update.yml --limit $2
+          if [ $? -ne 0 ]
+                then
+                  echo "ERROR"
+                  exit 2
+          fi
+          ansible-playbook -i hosts/verb_hosts ardana-update-status.yml --limit $2
+          ;;
 
 
         test)
